#%RAML 1.0 DataType
properties:
  key:
    type: string
    maxLength: 100
    example: "Bridge-91734"
  value:
    type: string
    maxLength: 1
    example: "1"
  expiration:
   type: integer
   required: false