#%RAML 1.0 DataType
properties:
  Key:
    type: string
    maxLength: 100
    example: "spectre-freefb-639178250106"
  Value:
    description: Holds the value of the key.
    type: string
    maxLength: 1
    example: "1"
  Expiration:
    description: Unix timestamp that sets timeout on key.
    type: integer
    required: false