#%RAML 1.0 DataType
properties:
  client-id:
    description: Client Id for authentication purposes.
    displayName: X-Client-Id
    required: true
    type: string
    minLength: 10
  client-secret:
    displayName: X-Client-Secret
    description: Client Secret for authentication purposes.
    required: true
    type: string
    minLength: 10
  correlation-Id:
    displayName: X-Correlation-Id
    description: Client Secret for authentication purposes.
    required: true
    type: string
    minLength: 5